name: test demo

on:
  push:
    branches: develop
    
  workflow_dispatch:

jobs:
    test:
        runs-on: vicky-runner

        steps:
           - name: testone
             uses: actions/checkout@v4
             with:
                path: 'develop'
