name: test demo

on:
  push:
    branches: main
    
  workflow_dispatch:

jobs:
    test:
        runs-on: self-hosted

        steps:
           - name: testone
             uses: actions/checkout@v4
             with:
                path: 'main'
